spring.application.name=SpringPlayMySongs
# Define o tamanho máximo de UM arquivo
spring.servlet.multipart.max-file-size=10MB

# Define o tamanho máximo da REQUISIÇÃO inteira (arquivo + textos)
spring.servlet.multipart.max-request-size=10MB